spring:
  application:
    name: EUREKA-SERVER
server:
  port: 9080

eureka:
  server:
    enable-self-preservation: false
    renewalPercentThreshold: 0.33
  instance:
    hostname: localhost
    nonSecurePort: ${server.port}
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/